### ISSUE TITLE
☝️ Call for maintainers

### ISSUE THREAD

**Issue by courentin** [lalalilo/athena-utils#15]
Hello,

This project has been supported by @lalalilo for a while. However, we are not using this package anymore which make it hard to review and validate PRs on this repo.

If you are actively using this project, please contact us!

**Comment by nicor88** [comment]
@courentin is there a possible interest to move the repo under [dbt-athena](https://github.com/dbt-athena) org and eventually share the keys of pypi with core maintainers of dbt-athena?

**Comment by courentin** [comment]
Definitely, I can transfer the ownership of the repo to dbt-athena if you'd like!

@nicor88 are you one of the core maintainers?

**Comment by nicor88** [comment]
@courentin yes, also @Jrmyy @jessedobbelaere @mattiamatrix

**Comment by Jrmyy** [comment]
👋🏻 Hello @courentin 
If it is ok, could you transfer the ownership to dbt-athena please ? :)

**Comment by courentin** [comment]
Hello, yes definitely, I'm doing it now :)

**Comment by courentin** [comment]
@Jrmyy I can't transfer it to dbt-athena because of:

<img width="719" alt="Screenshot 2023-06-15 at 12 03 34" src="https://github.com/lalalilo/athena-utils/assets/12371832/c1b225bd-bd7c-4a83-a138-8fbcfd812e02">

Would it be possible to temporarily allow me to create a public repo in dbt-athena?

**Comment by mattiamatrix** [comment]
Or you can probably make @Jrmyy (or me) admin of this project and we might be able to transfer it to dbt-athena

**Comment by courentin** [comment]
Unfortunately I can't
<img width="723" alt="Screenshot 2023-06-15 at 12 58 50" src="https://github.com/lalalilo/athena-utils/assets/12371832/be2406c3-856e-48f5-ad9d-0a973528a9e4">

**Comment by mattiamatrix** [comment]
Can you try now @courentin?

**Comment by courentin** [comment]
Tested to transfer to @mattiamatrix , @Jrmyy and dbt-athena but I still get the same error :/

Maybe @Jrmyy if you delete your fork it could work:
<img width="727" alt="Screenshot 2023-06-15 at 13 56 48" src="https://github.com/lalalilo/athena-utils/assets/12371832/e5f0f79f-4df1-4891-8e03-5179b58c67bc">

**Comment by courentin** [comment]
Actually it did work, I had to accept your invitation

Congrats you're now the owner of this repository!
